# Site settings
title: Reevoo Engineering
email: engineering@reevoo.com
description: "Reevoo Engineering blog, documentation and open sourced projects."
baseurl: ""
url: http://reevoo.github.io
twitter_username: DevAtReevoo
github_username:  reevoo

exclude:
- Gemfile
- Gemfile.lock
- README.md
- .travis.yml
- .gitignore
- LICENSE
- vendor
- script

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
